FROM ubuntu:20.04

# Setup the locales
RUN apt-get update && apt-get install -y locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    file \
    lsb-release \
    man \
    python \
    python3 \
    qemu \
    qemu-user-static \
    vim
